{% set name = "ggcat" %}
{% set version = "1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('ggcat', max_pin="x") }}

source:
  git_url: https://github.com/algbio/ggcat.git
  git_rev: v1.1
  git_depth: 1


requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}

test:
  commands:
    - ggcat --help

about:
  home: "https://github.com/algbio/ggcat"
  license: MIT
  license_family: MIT
  summary: |
    "Compacted and colored de Bruijn graph construction and querying."
  dev_url: "https://github.com/algbio/ggcat"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - guilucand
  identifiers:
    - doi:10.1101/gr.277615.122
